version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: autosouq_db
    ports:
      - '5433:5432' # host:container (expose DB on localhost:5433 to match provided connection string)
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
